### PR TITLE
Convert Vogen Hash Structure to Vogen-like Hash Structure

### PR DESCRIPTION
**Pull request by Sewer56**
## Context

As part of [Use NexusMods.Hashing.xxHash repo](https://github.com/Nexus-Mods/NexusMods.Archives.Nx/issues/8), we want to be using the `Hash` type in our library verbatim, rather than performing conversion to and from `Hash` type.

Issue is we use [Vogen](https://github.com/SteveDunn/Vogen) for generating the Hash type. However, `Vogen` introduces 2 fields into the structure:

- `IsInitialized`
- `StackTrace` (Debug Build Only)

The Nx Library requires this field to be its native size (8 bytes); so we need to compromise.

## Changes

This PR is pretty simple.

I took the autogenerated Vogen code, and threw it into the `Hash` struct directly, while removing the code that relies on the `Initialized` field. Then I added an assertion that Hash is 8 bytes.

I had a good look through the use of that field. For our use cases, the presence of Initialized field should not make a difference.

### CODE REVIEW

**Comment by halgari** [comment]
Why can't we just convert to and from this value inside NX? Even if we have to use ulong in the NX structures that's fine with me, this seems like a change that is only required due to the incidental complexity of NX. NX wants to load and store data a certain way so now we have to modify the Hashing lib? We can probably do this instead by a converter property inside NX

**Comment by Sewer56** [comment]
I'm happy (and in fact would prefer to) do that. I was just under the impression that you would have preferred we used the `Hash` type directly since you're generally in favour of integrating our libraries more closely.

One of your original points raised was 'why do we have to convert between our own data types if we both are part of the same (larger) project'. Therefore I just assumed you would have wanted it this way, hence this approach.

If you're fine with me just making extension methods instead (e.g. `GetHash()`), then please close this PR; and I'll add the relevant extensions in Nx PR.

**Comment by halgari** [comment]
Can't the NX structures use ulong internally and convert on-the-fly with a property?

**Comment by Sewer56** [comment]
> Can't the NX structures use ulong internally and convert on-the-fly with a property?

Yes, that's what I'd prefer to do.

Vogen uses up another register than passing the value around (due to extra data in struct); so I'd make both publicly available.

Edit: I played around with JIT and found out that if consumer needs raw value, the JIT is smart enough to elide the unneeded boolean IsInitialized value in certain scenarios. But not all.

Anyway, I did the changes on Nx PR to expose this via property. Am going for a nap now.

**Pull request closed without merging**
